/** v4 for plbs */
'GET /v4/ApiSms-sendRegistSms.htm' => 'v4-ApiSms-sendRegistSms', //发验证码
'POST /v4/ApiAuth-checkPhone.htm' => 'v4-ApiAuth-checkPhone', //检查手机号是否已用
'POST /v4/ApiAuth-register.htm' => 'v4-ApiAuth-register', //注册
'POST /v4/ApiAuth-login.htm' => 'v4-ApiAuth-login', //登录
'POST /v4/ApiAuth-sign.htm' => 'v4-ApiAuth-sign', //登录
'DELETE /v4/ApiAuth-logout.htm' => 'v4-ApiAuth-logout', //登出
'PUT /v4/ApiAuth-reset.htm' => 'v4-ApiAuth-reset', //重置密码
'GET /v4/ApiAccount-info.htm' => 'v4-ApiAccount-info', //获取用户信息&员工信息&获取企业主信息
'GET /v4/ApiAccount-personalProgresses.htm' => 'v4-ApiAccount-personalProgresses', //企业主：员工学习进度
'GET /v4/ApiAccount-courseProgresses.htm' => 'v4-ApiAccount-courseProgresses', //企业主：课程参与度
'GET /v4/ApiAccount-testProgresses.htm' => 'v4-ApiAccount-testProgresses', //企业主：考试合格率
'GET /v4/ApiAccount-enterpriseCourses.htm' => 'v4-ApiAccount-enterpriseCourses', //员工：企业专用课程列表
'GET /v4/ApiAccount-courses.htm' => 'v4-ApiAccount-courses', //用户：参与过的课程列表
'POST /v4/ApiAccount-course.htm' => 'v4-ApiAccount-course', //用户：参与过的课程列表
'GET /v4/ApiAccount-favorites.htm' => 'v4-ApiAccount-favorites', //用户：收藏夹
'GET /v4/ApiAccount-resume.htm' => 'v4-ApiAccount-resume', //用户：简历
'PUT /v4/ApiAccount-resume.htm' => 'v4-ApiAccount-resume', //用户：更新简历
'GET /v4/ApiBase-categorys.htm' => 'v4-ApiBase-categorys', //获取分类列表
'GET /v4/ApiCourse-courses.htm' => 'v4-ApiCourse-courses', //获取课程列表
'GET /v4/ApiCourse-course.htm' => 'v4-ApiCourse-course', //获取课程详情
'GET /v4/ApiCourse-lessons.htm' => 'v4-ApiCourse-lessons', //获取课时列表
'GET /v4/ApiCourse-lesson.htm' => 'v4-ApiCourse-lesson', //获取课时详情
'GET /v4/ApiCourse-tests.htm' => 'v4-ApiCourse-tests', //获取随机试题
'POST /v4/ApiAccount-test.htm' => 'v4-ApiAccount-testing', //提交测试

'GET /v4/ApiAccount-personalProgresses.htm' => 'v4-ApiAccount-personalProgresses', //企业主：员工学习进度
'GET /v4/ApiAccount-courseProgresses.htm' => 'v4-ApiAccount-courseProgresses', //企业主：课程参与度
'GET /v4/ApiAccount-testProgresses.htm' => 'v4-ApiAccount-testProgresses', //企业主：考试合格率
'GET /v4/ApiAccount-enterpriseCourses.htm' => 'v4-ApiAccount-enterpriseCourses', //员工：企业专用课程列表
'GET /v4/ApiArtic
